# Generated by Django 4.2.5 on 2023-12-13 09:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch_timings', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('key_features', models.TextField()),
                ('course_details', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='jopForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_city', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('degree_college', models.CharField(max_length=255)),
                ('passed_out_year', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post_graduation', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_degree_college', models.CharField(blank=True, max_length=255, null=True)),
                ('pg_passed_out_year', models.IntegerField(blank=True, null=True)),
                ('relevant_experience', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_person_contact', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studentuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(default=True, max_length=50)),
                ('joining_date', models.DateField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('actual_fees', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to='user_resumes/')),
                ('batch', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('course', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('present', models.BooleanField(default=False, null=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('max_marks', models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternative_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('graduation', models.CharField(max_length=255)),
                ('created_date', models.DateField()),
                ('status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('trainer', models.ManyToManyField(to='main.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='softskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('topic', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('max_performance', models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('marks', models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('max_marks', models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ManyToManyField(to='main.trainer'),
        ),
        migrations.CreateModel(
            name='communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('topic', models.TextField(null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='admissionform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Name', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=12)),
                ('Alternate_Mobile', models.CharField(max_length=12)),
                ('Tranier', models.CharField(choices=[('Mr.Srinivas', 'Mr.Srinivas'), ('Mr.Madhukar', 'Mr.Madhukar'), ('Mr.Manohar', 'Mr.Manohar'), ('Mr.Suresh', 'Mr.Suresh'), ('Mr.PVR', 'Mr.PVR'), ('O', 'Other')], max_length=20)),
                ('Mode_of_Traning', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=10)),
                ('Batch_timings', models.CharField(max_length=5)),
                ('DateOfjoining', models.DateField()),
                ('Batch_Number', models.CharField(max_length=5)),
                ('Qulification', models.CharField(max_length=10)),
                ('Work_experience', models.CharField(max_length=10)),
                ('Experience_or_Fresher', models.CharField(max_length=10)),
                ('Backlogs', models.CharField(max_length=5)),
                ('Linked', models.CharField(max_length=50)),
                ('Instagram', models.CharField(max_length=30)),
                ('Image', models.ImageField(null=True, upload_to='images/')),
                ('course_interest', models.CharField(choices=[('EASIER', 'Because this is easier than other courses.'), ('INTEREST', 'I absorbed myself I am quite interested on this course.'), ('SUGGESTION', 'My friend suggestion or parents suggestion.'), ('DEMAND', 'This course have highest demand in market.')], max_length=20)),
                ('v_cube_reason', models.CharField(choices=[('TRAINERS', 'VCUBE have professional trainers and process is good'), ('TRENDING', 'VCUBE is trending institute'), ('FRIEND', 'My friend suggestion'), ('ASSISTANCE', 'Because of 100 % assistance')], max_length=20)),
                ('expectations', models.CharField(choices=[('PLACEMENTS', '100 % placements'), ('KNOWLEDGE', 'Best training and best knowledge on particular course'), ('GUIDANCE', 'Best guidance + placement assistance'), ('NONE', 'No expectations')], max_length=20)),
                ('weakness', models.CharField(choices=[('FEAR', 'Stage fear'), ('COMMUNICATION', 'Lack of communication'), ('KNOWLEDGE', 'Lack of subject knowledge'), ('ALL', 'All the above')], max_length=20)),
                ('test_importance', models.CharField(choices=[('YES', 'Yes, it is'), ('NO', 'No'), ('UNKNOWN', 'I don’t know')], max_length=20)),
                ('mock_value', models.CharField(choices=[('YES', 'Yes, it is'), ('NO', 'No'), ('UNKNOWN', 'I don’t know')], max_length=20)),
                ('hear_about_us', models.CharField(choices=[('SOCIAL', 'Social media'), ('FRIEND', 'Friends reference'), ('RANDOM', 'Randomly')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
    ]
